### ISSUE TITLE
Question about using onpage() vs just page() ?

### ISSUE THREAD

**Issue by ferozed** [segment-integrations/analytics.js-integration-segmentio#43]
I was looking at the code of this extension. This may be a newbie question - but, why is this extension using `onpage()` and `ontrack()` events, and not just overriding `page` and `track` from the `Integration` ? For eg. like the google-analytics extension?

**Comment by f2prateek** [comment]
It was done historically since we didn't customers to accidentally disable the Segment integration by sending 'Segment.io: false' or 'All: false'. We may revisit this at some point in the future though.
